name: python V2rayCollector Script

on:
  schedule:
    - cron: '*/300 * * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure Git
        run: |
          git config --global user.email "hasoonhandavi@gmail.com"
          git config --global user.name "dasilva128"
          git remote set-url origin https://github.com/dasilva128/Mysub.git
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install beautifulsoup4
          python -m pip install speedtest-cli

      - name: Run Python script
        run: |
          python main.py  # Replace with your script's path
          git add -A
          git commit -m "The servers have been updated✔ - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git pull --rebase origin main
          git push
